### ISSUE TITLE
possible feature?

### ISSUE THREAD

**Issue by skibz** [jonschlinkert/file-reader#1]
```
//=> { a: [Function: aaa], b: [Function: bbb], c: [Function: ccc] } 
read('*.js');
read('*.txt');
//=> { a: 'AAA', b: 'BBB', c: 'CCC' } 
read('*.{yml,json}');
//=> { a: { a: 'a' }, b: { b: 'b' }, c: { c: 'c' } } 
```

given the above functionality, is this library able to do something like this:

```
read('somethingunique.*');
```

and return a mapping of all files (any extension) with the name `somethingunique`?

**Comment by jonschlinkert** [comment]
Really sorry, I thought i replied to this. I had a response typed out and everything!  as long as the extensions in all of the globbed file paths are mapped to a reader,  this is something the lib should handle.
